"""Vending machine: a State-driven machine over a pluggable item source."""

from lld.vending_machine.beverages import (
    BasicBeverage,
    Beverage,
    BeverageDecorator,
    BeverageFactory,
    ExtraMilk,
    ExtraShot,
    Sweetened,
)
from lld.vending_machine.models import (
    CashBox,
    Coin,
    DispenseFailedError,
    Dispenser,
    IllegalActionError,
    Ingredient,
    InsufficientChangeError,
    InsufficientFundsError,
    ItemSource,
    Note,
    OutOfIngredientError,
    OutOfStockError,
    Product,
    Recipe,
    Reservation,
    Slot,
    SlotFullError,
    StockListener,
    Transaction,
    UnknownSlotError,
)
from lld.vending_machine.services import (
    CoffeeBar,
    IngredientInventory,
    Inventory,
    MaintenanceLog,
    MotorDispenser,
    VendingMachine,
)
from lld.vending_machine.states import (
    Dispensing,
    HasMoney,
    Idle,
    MachineState,
    OutOfService,
)
from lld.vending_machine.strategies import ChangeMaker, GreedyChangeMaker, MinimalChangeMaker

__all__ = [
    "BasicBeverage",
    "Beverage",
    "BeverageDecorator",
    "BeverageFactory",
    "CashBox",
    "ChangeMaker",
    "CoffeeBar",
    "Coin",
    "DispenseFailedError",
    "Dispenser",
    "Dispensing",
    "ExtraMilk",
    "ExtraShot",
    "GreedyChangeMaker",
    "HasMoney",
    "Idle",
    "IllegalActionError",
    "Ingredient",
    "IngredientInventory",
    "InsufficientChangeError",
    "InsufficientFundsError",
    "Inventory",
    "ItemSource",
    "MachineState",
    "MaintenanceLog",
    "MinimalChangeMaker",
    "MotorDispenser",
    "Note",
    "OutOfIngredientError",
    "OutOfService",
    "OutOfStockError",
    "Product",
    "Recipe",
    "Reservation",
    "Slot",
    "SlotFullError",
    "StockListener",
    "Sweetened",
    "Transaction",
    "UnknownSlotError",
    "VendingMachine",
]
