#!/usr/bin/env python3
"""Generate the section index pages (docs/**/index.md) from CATALOGUE.md.

Writes seven section indexes (hld/fundamentals, hld/case-studies, lld/fundamentals,
lld/patterns, lld/problems, cheatsheets, mocks) and two hub pages (hld, lld).
docs/index.md and docs/roadmap.md are hand-written and never touched.

Usage: python scripts/gen_indexes.py            # (re)write the index pages
       python scripts/gen_indexes.py --check    # exit 1 if any page on disk differs
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

sys.path.insert(0, str(Path(__file__).parent))
import catalogue  # noqa: E402

ROOT = catalogue.ROOT
DOCS = ROOT / "docs"
COVERS_MAX = 140
COVERS_MIN = 60  # keep adding sentences until the cell is at least this long
GENERATED_NOTE = "<!-- Generated by scripts/gen_indexes.py from CATALOGUE.md - do not edit by hand. -->"
TIER_LEGEND = (
    "Tiers: **P0** must be solid before any interview, **P1** is expected of a strong SDE2, "
    "**P2** is stretch material for when the rest is done."
)


@dataclass(frozen=True)
class Section:
    dir: str  # relative to docs/, e.g. "hld/fundamentals"
    category: str
    nav_title: str  # short name used in hub lists ("Fundamentals")
    title: str  # page title
    description: str  # front-matter description (one sentence)
    intro: str  # 2-4 sentences
    blurb: str  # one line used in the hub "Sections" list


@dataclass(frozen=True)
class Hub:
    dir: str
    title: str
    description: str
    intro: str
    sections: tuple[str, ...]


SECTIONS: tuple[Section, ...] = (
    Section(
        dir="hld/fundamentals",
        category="hld-fundamental",
        nav_title="Fundamentals",
        title="HLD fundamentals",
        description=(
            "The building blocks of system design interviews: framework, estimation, networking, "
            "storage, replication, partitioning, consistency, messaging, resilience and more."
        ),
        intro=(
            "These are the building blocks every system design answer is assembled from: the "
            "45-minute framework, estimation, networking, load balancing, caching, databases and "
            "storage engines, replication and partitioning, transactions, consistency models, "
            "messaging, consensus, resilience, observability and security. Each page ends with how "
            "to raise the topic in the room, the follow-up questions interviewers ask and a "
            "self-check. Read the P0 pages in order before your first case study; they introduce "
            "the vocabulary and the default architecture every case study extends. Pages with a "
            "Python implementation ship a tested module under `code/hld/` that you can run and "
            "modify."
        ),
        blurb="the concepts and trade-offs every case study builds on",
    ),
    Section(
        dir="hld/case-studies",
        category="hld-case-study",
        nav_title="Case studies",
        title="HLD case studies",
        description=(
            "Thirty-one system design case studies, each with requirements, estimation, API, data "
            "model, deep dives, scaling, trade-offs and a tested Python snippet."
        ),
        intro=(
            "Each case study follows the same spine: requirements, estimation, API, data model, v1 "
            "design, 3-5 deep dives, scaling, trade-offs and a 45-minute pacing table. Start with "
            "the P0 systems; they cover the archetypes (read-heavy fan-out, real-time stateful, "
            "contended inventory, partitioned key-value storage) that the P1 and P2 systems are "
            "variations of. Every study ships one key Python snippet under `code/hld/` with tests, "
            "so you can see the crux - fan-out, seat holds, matching, the ledger - as running code "
            "rather than a box on a diagram."
        ),
        blurb="the systems interviewers ask for, solved end to end",
    ),
    Section(
        dir="lld/fundamentals",
        category="lld-fundamental",
        nav_title="Fundamentals",
        title="LLD fundamentals",
        description=(
            "Object-oriented Python, SOLID, UML in Mermaid, the LLD interview framework, "
            "concurrency and clean testable code for low-level design rounds."
        ),
        intro=(
            "What you need before any object-oriented design round in Python: the language "
            "features interviewers expect you to use fluently, SOLID and the principles beyond it, "
            "UML in Mermaid, the LLD interview framework, concurrency primitives and clean, "
            "testable code. Each page pairs the concept with before/after Python and exercises "
            "with collapsed solutions. Read the P0 pages first, then move on to the patterns and "
            "problems; come back here whenever a reviewer comment or a failed exercise points at "
            "a gap."
        ),
        blurb="Python, SOLID, UML, concurrency and the LLD framework",
    ),
    Section(
        dir="lld/patterns",
        category="design-pattern",
        nav_title="Design patterns",
        title="Design patterns",
        description=(
            "The Gang of Four and enterprise patterns that LLD interviews reward, each with a "
            "classDiagram, a tested Python module, the Pythonic variant and where it is used."
        ),
        intro=(
            "The Gang of Four patterns plus the enterprise patterns (Repository, Unit of Work, "
            "Dependency Injection, Specification, Pipeline, Event Bus) that LLD interviews actually "
            "reward. Every page gives the intent, a classDiagram whose names match a tested module "
            "in `code/patterns/`, the Pythonic variant that is often enough, the classic confusions "
            "and the LLD problems where the pattern earns its place. Start with the overview and "
            "the P0 patterns - Strategy, State, Observer, Factory Method, Builder, Decorator, "
            "Command - which cover most of what interviewers ask you to name and justify."
        ),
        blurb="the patterns worth naming, with tested Python and the classic confusions",
    ),
    Section(
        dir="lld/problems",
        category="lld-problem",
        nav_title="Problems",
        title="LLD problems",
        description=(
            "Thirty-six machine-coding problems solved the interview way: requirements, entities, "
            "class and sequence diagrams, then a complete tested Python package."
        ),
        intro=(
            "Thirty-six machine-coding problems, each solved the way you would in a 45-minute "
            "round: requirements and assumptions, entities, a classDiagram, the key flows, then a "
            "complete, tested Python package under `code/lld/` with an injected clock, explicit "
            "locking and a runnable demo. Start with the P0 problems - parking lot, elevator, "
            "vending machine, in-memory cache, rate limiter, tic-tac-toe, Splitwise and movie "
            "ticket booking - which together exercise every pattern and concurrency idea the rest "
            "reuse. Each page closes with the follow-ups interviewers ask and a pacing table for "
            "that specific problem."
        ),
        blurb="machine-coding problems with complete tested packages",
    ),
    Section(
        dir="cheatsheets",
        category="cheatsheet",
        nav_title="Cheatsheets",
        title="Cheatsheets",
        description=(
            "Dense reference tables for the night before: latency numbers, selection matrices, "
            "consistency tables, the problem-to-pattern map, checklists and a glossary."
        ),
        intro=(
            "Dense, scannable tables for the night before and the minutes between rounds: the "
            "canonical latency and estimation numbers every page on this site uses, database and "
            "queue selection matrices, consistency and isolation tables, the problem-to-pattern "
            "map, round checklists, the clarifying-question bank and a glossary. They summarise; "
            "the linked pages explain. Keep the latency sheet open while you practise estimation "
            "until the orders of magnitude are automatic."
        ),
        blurb="reference tables to revise from",
    ),
    Section(
        dir="mocks",
        category="mock-interview",
        nav_title="Mock interviews",
        title="Mock interviews",
        description=(
            "Six full interview transcripts, three HLD and three LLD, with a minute-by-minute "
            "timeline, evolving diagrams, a rubric and practice variants."
        ),
        intro=(
            "Six full transcripts - three HLD, three LLD - with the clock running: what the "
            "interviewer says, what the candidate says, draws and writes at each minute, and how "
            "the diagram evolves from a v1 skeleton to the version after the deep dives. Each mock "
            "ends with a rubric showing what below-bar, SDE2 and exceeds look like, with quotes "
            "from the transcript, plus three variants to redo alone. Read the matching case study "
            "or problem first, then attempt the prompt yourself before reading the transcript."
        ),
        blurb="full transcripts with timelines and rubrics",
    ),
)

HUBS: tuple[Hub, ...] = (
    Hub(
        dir="hld",
        title="High-level design (HLD)",
        description=(
            "System design for SDE2 interviews: the fundamentals behind every architecture and "
            "the case studies interviewers ask for."
        ),
        intro=(
            "System design rounds test whether you can turn a vague product prompt into a "
            "justified architecture in 45 minutes. This section has two parts: the fundamentals "
            "explain the building blocks and the trade-offs behind them; the case studies apply "
            "them to the systems interviewers actually ask for. Work through the P0 fundamentals, "
            "then the P0 case studies, then use the mock interviews to rehearse against the clock."
        ),
        sections=("hld/fundamentals", "hld/case-studies"),
    ),
    Hub(
        dir="lld",
        title="Low-level design (LLD)",
        description=(
            "Object-oriented design for SDE2 interviews: Python fundamentals, design patterns and "
            "machine-coding problems with tested packages."
        ),
        intro=(
            "Low-level design rounds test whether you can turn requirements into clean, "
            "extensible, working classes - often while coding live. This section covers the "
            "Python and design fundamentals interviewers expect, the patterns worth naming and the "
            "machine-coding problems that come up most often, each with a tested package. Start "
            "with the LLD interview framework, learn the P0 patterns, then solve the P0 problems "
            "against the clock."
        ),
        sections=("lld/fundamentals", "lld/patterns", "lld/problems"),
    ),
)

SECTION_BY_DIR = {s.dir: s for s in SECTIONS}


# ----------------------------------------------------------------------------- helpers
def rel_link(from_page: str, to_page: str) -> str:
    """Relative link from one docs page to another (both repo-relative paths)."""
    start = PurePosixPath(from_page).parent
    return os.path.relpath(to_page, start=str(start)).replace(os.sep, "/")


def first_sentence(text: str, min_chars: int = COVERS_MIN) -> str:
    """First sentence (split at '. ' + uppercase/digit/paren); keeps appending sentences
    while the result is shorter than `min_chars`, so a two-word tagline is not the whole cell."""
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9(\"'`])", text.strip())
    out = ""
    for part in parts:
        if out and len(out) >= min_chars:
            break
        out = f"{out} {part}".strip()
    return out


def trim(text: str, limit: int = COVERS_MAX) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    if " " in cut:
        cut = cut[: cut.rfind(" ")]
    return cut.rstrip(" ,;:-(") + "…"


def covers(page: catalogue.Page) -> str:
    """The 'Covers' cell: first sentence of the scope (or brief FR line), trimmed."""
    if page.category == "lld-problem" and page.brief:
        text = page.brief.splitlines()[0].strip()
        text = re.sub(r"^FR:\s*", "", text)
    else:
        text = re.sub(r"\bSee brief [A-Z]{2}-\d{2}\.?", "", page.scope).strip()
    text = trim(first_sentence(text))
    return text.replace("|", "\\|")


def front_matter(title: str, description: str) -> str:
    return f"---\ntitle: {title}\ndescription: {description}\n---\n"


def section_pages(pages: list[catalogue.Page], section: Section) -> list[catalogue.Page]:
    return [p for p in pages if p.section == section.dir]


# ----------------------------------------------------------------------------- renderers
def render_section(pages: list[catalogue.Page], section: Section) -> str:
    index_path = f"docs/{section.dir}/index.md"
    rows = section_pages(pages, section)
    out: list[str] = [front_matter(section.title, section.description), GENERATED_NOTE, ""]
    out += [f"# {section.title}", "", section.intro, "", TIER_LEGEND, ""]
    out += ["## Start here (P0)", ""]
    p0 = [p for p in rows if p.tier == "P0"]
    if p0:
        out += [f"- [{p.title}]({rel_link(index_path, p.path)})" for p in p0]
    else:
        out.append("- No P0 pages in this section; start from the top of the table below.")
    out += ["", "## All pages", "", "| # | Page | Tier | Covers |", "|---|---|---|---|"]
    for n, p in enumerate(rows, 1):
        out.append(f"| {n} | [{p.title}]({rel_link(index_path, p.path)}) | {p.tier} | {covers(p)} |")
    out.append("")
    return "\n".join(out)


def render_hub(pages: list[catalogue.Page], hub: Hub) -> str:
    index_path = f"docs/{hub.dir}/index.md"
    out: list[str] = [front_matter(hub.title, hub.description), GENERATED_NOTE, ""]
    out += [f"# {hub.title}", "", hub.intro, "", "## Sections", ""]
    for sec_dir in hub.sections:
        sec = SECTION_BY_DIR[sec_dir]
        count = len(section_pages(pages, sec))
        link = rel_link(index_path, f"docs/{sec.dir}/index.md")
        out.append(f"- [{sec.nav_title}]({link}) - {count} pages: {sec.blurb}")
    out += ["", "## Start here (P0)", ""]
    for sec_dir in hub.sections:
        sec = SECTION_BY_DIR[sec_dir]
        p0 = [p for p in section_pages(pages, sec) if p.tier == "P0"]
        if not p0:
            continue
        out += [f"### {sec.nav_title}", ""]
        out += [f"- [{p.title}]({rel_link(index_path, p.path)})" for p in p0]
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def render_all(pages: list[catalogue.Page]) -> dict[str, str]:
    """Map of repo-relative path -> content for every generated page."""
    known = {s.dir for s in SECTIONS}
    unknown = sorted({p.section for p in pages} - known)
    if unknown:
        raise SystemExit(f"gen_indexes: catalogue pages in sections without an index: {unknown}")
    files: dict[str, str] = {}
    for sec in SECTIONS:
        files[f"docs/{sec.dir}/index.md"] = render_section(pages, sec)
    for hub in HUBS:
        files[f"docs/{hub.dir}/index.md"] = render_hub(pages, hub)
    return files


# ----------------------------------------------------------------------------- main
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if any index page on disk differs")
    args = parser.parse_args(argv)

    pages = catalogue.load()
    errors = catalogue.validate(pages)
    if errors:
        for e in errors:
            print("CATALOGUE ERROR:", e, file=sys.stderr)
        return 1
    files = render_all(pages)

    if args.check:
        bad = 0
        for rel, content in files.items():
            path = ROOT / rel
            if not path.exists():
                print(f"MISSING: {rel}")
                bad += 1
            elif path.read_text(encoding="utf-8") != content:
                print(f"DIFFERS: {rel}")
                bad += 1
        if bad:
            print(f"gen_indexes --check: {bad} of {len(files)} index pages out of date (run scripts/gen_indexes.py)")
            return 1
        print(f"gen_indexes --check: {len(files)} index pages up to date")
        return 0

    written = unchanged = 0
    for rel, content in files.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_text(encoding="utf-8") == content:
            unchanged += 1
            continue
        path.write_text(content, encoding="utf-8")
        written += 1
        print(f"wrote {rel}")
    print(f"gen_indexes: {written} written, {unchanged} unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
